
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: finance_track_development

test:
  <<: *default
  database: finance_track_test

production:
  <<: *default
  database: finance_track_production
  username: finance_track
  password: <%= ENV["BUDGET_TRACKER_DATABASE_PASSWORD"] %>
